config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users

     resources :pages, only: [:index]

      resources :clusters, only: [:index, :new, :create] do
          resources :starts, only: [:new, :create]
          resources :associations, only: [:index]
      end

      resources :starts, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  # Defines the root path route ("/")
  root "clusters#index"
end

app/models/cluster.rb
class Cluster < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :associations, foreign_key: :cluster_id, dependent: :destroy
  has_many :starts, through: :associations, foreign_key: :cluster_id, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  # validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  before_action :set_cluster, only: %i[show edit update destroy]

  # GET /clusters or /clusters.json
  def index
    @clusters = Cluster.all.includes([:user])
  end

  # GET /clusters/1 or /clusters/1.json
  def show; end

  # GET /clusters/new
  def new
    @cluster = Cluster.new
  end

  # GET /clusters/1/edit
  def edit; end

  # POST /clusters or /clusters.json
  def create
    @cluster = Cluster.new(cluster_params)
    @cluster.user = current_user

    respond_to do |format|
      if @cluster.save
        format.html { redirect_to clusters_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @cluster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clusters/1 or /clusters/1.json
  def update
    respond_to do |format|
      if @cluster.update(cluster_params)
        format.html { redirect_to cluster_url(@cluster), notice: 'Cluster was successfully updated' }
        format.json { render :show, status: :ok, location: @cluster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clusters/1 or /clusters/1.json
  def destroy
    @cluster.destroy
    respond_to do |format|
      format.html { redirect_to clusters_url, notice: 'Cluster was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cluster
    @cluster = Cluster.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cluster_params
    params.require(:cluster).permit(:name, :icon)
  end
end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/views/clusters/_cluster.html.erb
<ul class="cluster-container">
<% @clusters.each do |cluster| %>
  <% if can? :manage, cluster %>
  <li class="cluster">
    <div class="cluster-image">
      <%= image_tag cluster.icon, alt: 'icon' %>
    </div>
    <h2><%= link_to cluster.name, cluster_associations_path(cluster_id: cluster.id) %></h2>
    <p>Transactions: <%= cluster.starts.count || 0 %></p>
  </li>
  <% end %>  
<% end %>
</ul>

app/views/clusters/_form.html.erb
<%= form_with(model: cluster) do |form| %>
  <% if cluster.errors.any? %>
    <div style="color: green">
      <h2><%= pluralize(cluster.errors.count, "error") %> prohibited this cluster from being saved:</h2>

      <ul>
        <% cluster.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>>

  <div class="categorie-input-container" >
    <%= form.select :icon, [
       ["Investment", "investment.png"], ["Bills", "bills.png" ],
       ["Healthcare", "health.png"], ["Education", "education.png"],
       ["Transportation", "public-transport.png"], ["Travels/Trips", "travel.png"],
       ["Food, Snacks, Restaurants", "food.png"], ["Gym and Self-care", "gym.png"],
       ["Entertainment", "entertainment.png"], ["Beauty", "beauty.png"], ["Shopping", "shopping.png"],
       ["Emergencies", "emergency.png"]
       ], class:'form-select' %>
  </div>
   <div class="add-t-container">
    <%= form.submit 'SAVE', class: "add-transaction"%>
  </div>

  <div class="button-back">
    <%= link_to "Back to clusters", clusters_path, class: "back-to" %> 
  </div>

<% end %>

app/views/clusters/create.html.erb
<h1>Clusters#create</h1>
<p>Find me in app/views/clusters/create.html.erb</p>

app/views/clusters/destroy.html.erb
<h1>Clusters#destroy</h1>
<p>Find me in app/views/clusters/destroy.html.erb</p>

app/views/clusters/edit.html.erb
<%# <h1>>Editing cluster</div>

<%= render 'form', cluster: @cluster %>

<%# <div>
  <%= link_to 'Show this cluster', @cluster %> |
  <%# <%= link_to 'Back to clusters', clusters_path %>
<%# </div> %>

app/views/clusters/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="cluster-section">
  <%= render partial: '/clusters/cluster' %>
  <div class="add-b-container">
    <%= link_to 'ADD NEW CATEGORY', new_cluster_path, class: 'add-category' %>
  </div>
</div>

app/views/clusters/new.html.erb
<div class="new-transaction">
  <h1>New cluster</h1>
  <%= render 'form', cluster: @cluster %>
</div>
<%# <div>
  <%= link_to 'Back to clusters', clusters_path %>
<%# </div> %>

app/views/clusters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cluster %>

<div>
  <%= link_to "Edit this cluster", edit_cluster_path(@cluster) %> |
  <%= link_to "Back to clusters", clusters_path %>
  <%= button_to "Destroy this cluster", @cluster, method: :delete %>
</div>

app/views/clusters/update.html.erb
<h1>Clusters#update</h1>
<p>Find me in app/views/clusters/update.html.erb</p>