config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users

     resources :pages, only: [:index]

      resources :clusters, only: [:index, :new, :create] do
          resources :starts, only: [:new, :create]
          resources :associations, only: [:index]
      end

      resources :starts, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  # Defines the root path route ("/")
  root "clusters#index"
end

app/models/association.rb
class Association < ApplicationRecord
  belongs_to :start
  belongs_to :cluster
end

app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
  def index
    @cluster = Cluster.find(params[:cluster_id])
    @starts = @cluster.associations.includes(:start).order('starts.created_at DESC').map(&:start)
  end
end

app/helpers/associations_helper.rb
module AssociationsHelper
end

app/views/associations/_association.html.erb
<%# <d id="<%= dom_id association %>

app/views/associations/_form.html.erb
<%# <%= form_with(model: association) do |form| %>
  <%# <% if association.errors.any? %>
    <%# <div id="error_explanation">
      <%# <h2><%= pluralize(association.errors.count, "error") %>

app/views/associations/create.html.erb
<h1>Associations#create</h1>
<p>Find me in app/views/associations/create.html.erb</p>

app/views/associations/destroy.html.erb
<h1>Associations#destroy</h1>
<p>Find me in app/views/associations/destroy.html.erb</p>

app/views/associations/edit.html.erb
<%# Nothing %>

app/views/associations/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="associations">
  <ul class="start-container cluster-container">
  <div class="cluster-transactions-header">
    <h2><%= @cluster.name %> <span><%= "Total $#{total_amount(@starts)}" %></span></h2>
  </div>

  <% if @starts.empty? %>
    <li>
      <h3>You do not have any registered charges yet</h3>
    </li>
  <% end %>
  <% @starts.each do |start| %>
    <% if can? :manage, Start %>
    <li>
      <div class="start-card">      
      <div class="start-image">
        <%= image_tag @cluster.icon %>
      </div>
      <div class="start-info">
        <h3><%= start.name %></h3>
        <h4><%= start.created_at %></h4>
      </div>
      </div>
      <p>
        <%= start.amount %>
      </p>
    </li>
    <% end %>
  <% end %>
  </ul>

  <div class="add-b-container">
    <%= link_to "Add a new transaction", new_start_path, class: "transaction-new-add-category" %>
  </div>
</div>

app/views/associations/new.html.erb
<%# <h1>New relation</h1>

<%= render 'form', association: @association %>

<%# <div>
  <%= link_to 'Back to relations', associations_path %>
<%# </div> %>

app/views/associations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @association %>

<div>
  <%= link_to 'Edit this relation', edit_association_path(@association) %> |
  <%= link_to 'Back to relations', associations_path %>
  <%= button_to 'Destroy this relation', @association, method: :delete %>
</div>

app/views/associations/update.html.erb
<h1>Associations#update</h1>
<p>Find me in app/views/associations/update.html.erb</p>